### ISSUE TITLE
Testing user experience

### ISSUE THREAD

**Issue by brockwsmith225** [bugenelu/JIB-0330#45]
Thorough in-context testing of user experience

**Acceptance Criteria:**
The user experience should work as intended

**Comment by shivamshah1999** [comment]
When password is not long enough or email is not entered and we hit "Submit," the textbox shifts to make space for this error message

![image](https://user-images.githubusercontent.com/25126647/114791589-c30aa300-9d54-11eb-9650-597e1eaf13f1.png)
